language: java

jdk:
- oraclejdk8

install: ./mvnw install -DskipTests -Dgpg.skip

sudo: required

services:
- docker

env:
  matrix:
  - secure: DtBhQpZozy+KBmOK47BIwU7ZYFY4xz+PmeKJppn8pYslpTQX4u43J/cHSq+Z/IYeG35/TCGZilB+cNPiOTs5ji6J/nYuxuFImRSrMVwDpxRkhnmuTMQqGuc+aPKKzWpMwmJuh+yEjGiKg8m3N62yeLnKBDRXmed7ArispEJaDQoOzNTxeXhIthYtS3l/uGo0Q1BYSmFMBZNhyJxQnXHi16KVbaxVlH+3Yn1OOSbCCCk8IS5+J2buKGv56GYRKfG2f3uQgFyfnVoWGFX+SAHIQWfjuSG5rmOzcktynXIoF1Y7ysjG2O6N7aJy/3Nd/08zv9hazYZW/Op8cc8NiqgUDhLI/4JiZRG23Ch2xd+Bww5sytoTR55dK8DBpJjOAYa2U4yRpCCiUBJQbsXjfAo5zJaI7d/OhxtDTVwLz0F6NM+QuAk63k/eoYafRckhsQbdwhBs9cBQFHZtQoh45jKD1QXlWkgH5d02MexljJaMbSSSk8uFsQIDYFcDWj5Wew9nm1kkzw2IA/U1T30ZGTnaw/C6x6lHoZsJs9gdupOHVy1BkWxnvfee45Ttsu9nuCFMJ47j85NoCp1RQmAxVHAO3/rW/8wC5r+b4vJj3Q/LhZO0fe+AN7c5p8poFOsGqyPtaryPESMerhWQ41YlYsyBjx/sFeJPfk7hBPdxvP63UG0=
  - secure: mTQcccIiwAQS7smIAGQzgOfDNMJk62DsmZbE2cGfTpIDeiInP/FGY3jQAu9/umrHximp80H2YBfUZy9uyKMmGBL1WRfsIKpRdLYcY9HM1B+Wv8qNAZ7dA9ahPnfLuevq5dm0VY1/DHnYdo6zjD7g3B8uEnwAeuK9U9DJ/iUm4zNVQ6V1nEaJ6dHM9XIxZo1JbI5i3lgyMqWDASkbzeSFULiQyD2hUBd/PT685yRQ9V6EubJxyLixb8UWanJYed6yBQrxbGK1kHasANRcfnH7b706APmi/OBMzjYjtoU/Z3K4D5ICpCBOEzeo1Oce6Pxsj6Q+CsaDyE8PgUlo8+SVAzXoQhtX6vp5y7EsijwZe0hZY/85xXoQqoF1YNj/wNfa9w3eEHn5Alc9Wnq5WvTTEKbsrEMNlJf5PfxdPpnaM+GbEXsSh1cCvRj4dA0EBRhx40eLgPhK0UaNFEb+y2n7RHlmRCJDJ25+6D4fgZHM4wzo7+WpU8nqsY0X/KlMDMGDXYGXxx26NHiOAKfstsPKp5FwqmNR4XZGtzkCt59GdCuRHbmlQTcyNTRfs+mHRMOQNnhNTO9p8FApsBX8rNIWApVCUjtniebQSsLUdWM660H9rINuLDL2Z5p3dmW8EGQDYRP+fi4x5PiZaYG9/zObttLtpFGDxvbW0FB+ijR2HDQ=

before_script: ./ui/build-ui.sh

script: ./ui/build-docker.sh

