language: java
jdk:
- oraclejdk8

install: ./mvnw install -DskipTests -Dgpg.skip

sudo: required

services:
- docker

env:
  global:
  - secure: caGYF1H+nGgMs3KaOLEt6Ne/CCq+KNps62WTx5aWewmt4J6Up+2+yhYIA9fLBZr1/XJHLg2ylwFkb97Q1NEqpC5HrFL9VISS/51TJGpmfgkZ6f8dwvHbI+MILYILHXGSyb0yBhx6vz/IZVYEMluci5Cw1JYSDYRWTRg8sBVWZscad3jfdLs4cQP851aaTEXRQEBwZhHfHOUTu6m6jMD7KSVJ8ObWPD++9is+Kcn6cvdNYr+RZRBBTgQsXFbtpjJyAcLvUDHBlipKbmDd8P0S1qGxEujepvPZUwQmPNgFh2BoDbDEndTKOvq1LfplbxBdeRDSu8TRWIom6mtn28iQmz23n/M1Gx2Sl+xvn2jqpAgPAFLW2voglsotsnjvSYXCZJOgMv9xtwpEequNzdKQO8JXmgiZHb4UJskZsvlhaZ6XGgJT425AJEJo/Qgn0YMCBrMt1GMX/xwKrnf/GJNyC8ldR5Ijq37weYUQ3kvbkmoM2JALVxqxxTEEGFh7M89/Pn1VYuE01gns4W5NicJ9fwfRVkWdiQY0wnxB/Idb3DCOckyZIwIEGjwmPet8bHZH087ljYxiDyUo5AWgAYdDMJA+O3XJkgV9fFguV8xHoqrH3O0r8agujipF/YpUGY3q3SY4I9TPqKzJS8fEDYAMcN6DOPPnQbozwC1OhZQcHNM=
  - secure: IyUIfBLOcWjj0zxeq1dEIvs51HfSOzVlymelF9mwawFDbLIEUcIZF/mI+x1rKDMx24hVo4/ER8VZ4zzUYu3Cxo1he9ICq9SNODIeygbfsI1qfheALAf+MSLMW/tKG+U9BCJtn6MBh+J2dDO1bya8H+8A7OooqsThChf5CVbRtBfiDy0q8H3WCeRr9AxTZvvV9tToG09IQyhCqQHHE/4NFNuFLeqw6LlUGrjLVvYLUiIwc1/dQGUjc4OkrUEB7x680Uv3Lr17vYMTAiWZVh2nwSY9sFumNVfs01EV/PsW4UhlHmK66TJO3LfHg3DoUrCthvt+bZTRwD0C+4IZjTXB9x9Zc64zfEo8PKjDeZ4apa0KY/cvxiwPvX0GWZgFpz8FIBagZ+nDyJRraBuOpAbxogiCdVnaqJPB/YSo2tZl0GMNCDE02FrKfkcyXP3JpyJs3C7YfOdEEPXZWcMm1yqbWrus29hj6eYNRuGTzH6zKlDEhAlo8imlLxkFFG8SDQMUroXLQxQCMQu6ymboQq5MD9hF6aGaripSW8H0ZkuLny+D7KvLkeO6gYZYB+e0SdxTFCmLamg7Tx/Skde5ErBCKJKEaDhhPE+MjlF2xankjJxp/KGEHShKG0e7Tzux+9aM/SXyCTJ/h7kjVP9e0VyyaIpYZwg/1lQCyf//t0vYIMI=

script: ./ui/build.sh

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build -t ofervelich/test:$TRAVIS_COMMIT .
- docker push ofervelich/test:$TRAVIS_COMMIT
