language: java
jdk:
- oraclejdk8

env:
  global:
    - secure: NJNSKtjUZtcfgpZ3vd9Vli9f0UzcFQEBoFykXSzzTleYyWkLhxDCkYm0VrBlBqb2KbMLKCzhZNFM5HhRafxlAzMqVDYej1ftKO3dVydeNYw7KeT0PdZqXZMkU9wZAXJUEyneTbiSGw78jxzxr+O3aGDFThmv160WlECmygkqB2wiM0hhlW/na9B2/lapHHYkXzm2RM5hjRd+C1CaBZopvKC+s7X7AgCrE2BcgQo9T0HAZDezfzVpjwv6lBcPwvQc/UVhY1fFw49PMfHPR5bxZpwQXq7zJgL/FnunwnsoMT0Rir2HyvZwY802jEXlerwdtYkxJqumiTg/PG5YSQYRAIpwvZU6f+tmnQCr4q1Kd66LmSlHSawf81rSO7Xk0n5H9QpBomWKngIp5F24SeN49Yo5kHwzSEXy60cqsFBGPBk27HrRGPrkvJsuALGvMOpMgrwdHJ7E35hxCJAHqjRiRhlc7RTFc2e18aiEOvxHM51WUOI5VMSQCUWnpl1Goy88Jhq4NKUqL+PWbDFUH/PVwNsmX/tduBRS5/ghuf0jMO1/VgGxqZTdreDqnUJg9SRyEJKrza6S/YCabSfSlXMExYdzNBa8XRmJxVqPDRUUQ8zLOGqy7meleWrMR35dcus4jNQdVeM4Mon526Y5Fr6Mvck73Lhe9XAQhNRY0rV2sqY=
    - secure: w1fX1qn3QP0iQz+M/1aGEISgTaUYJ4O9FOzLV0UCJRvDBTuDq5pZfy/QBbiUIDo4w1hHYjza85AaTqGV7h1+ozvVnVJK3pFYBRbAV2ZyXwN1fhFNj7cA6ECaMfo5Jbsp4XOaV74DZ0GFjJk4l6G9i/qCXUEDnsEJjLeOi2DXmaUpE/I2NBte0SpUoX1nNnTiJUyYjFbxAKED5PtlffmmrjI/L303vdQ63n5/AcZbMFBRakkHjqvfgfBOzECedUF9PNciXe/+JSNhVqSORW/6PT09sU0R7kIzwI+rzdhbvhQN0NhSMEmuWhldjuuWmF0O4wHHbYQSZME8/aNxh3gzh0TuzsnkV39eictspu3CDoj+7PEEFgpusg6zfMSP+DZzDV+seNQhPNw0Zshwn+xRf7kDIg87pw/DPnqozPTwO3aph0HB3QIYli1vgBJko5QTWHx5l0RuuOstqfK7u/E97lThKDkZVXI3PIXQbHLI6qRpmQQLBPRmNzfCCNxjO59Vx87Pnvl63HiW0tvhpToTrqiuF4SVDja7nWVTv7AJiDQ4k2bmOrmSxiL77GdzxQFQiG3xDJIUP2YlKlh5UxziIqjY2rjNld3pM53J+cqlxznvC23gc4PFgOR5qNPZf6uc5H2LOZZRVlln/5Pgk10fSzIMcokuD/7+zGrTwEK2T6M=
    - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

sudo: required

services:
  - docker

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw install -DskipTests -Dgpg.skip

script:
  - ./mvnw test && ./ui/build.sh

after_success:
  - if [ "$BRANCH" == "master" ]; then
    docker build -t apollologzio/test:$TRAVIS_COMMIT .;
    docker tag apollologzio/test:$TRAVIS_COMMIT logzio/apollo:latest;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push apollologzio/test:$TRAVIS_COMMIT;
    docker push apollologzio/test:latest;
    fi
