language: java
jdk:
- oraclejdk8
install: ./mvnw install -DskipTests -Dgpg.skip

sudo: required
services:
  - docker

script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - echo $PWD

script: ./scripts/build.sh